### ISSUE TITLE
Error when terminal does not support colors

### ISSUE THREAD

**Issue by heynemann** [heynemann/pyccuracy#33]
Traceback (most recent call last):
  File "/usr/bin/pyccuracy_console", line 134, in <module>
    main()
  File "/usr/bin/pyccuracy_console", line 106, in main
    create_progress()

  File "/usr/bin/pyccuracy_console", line 41, in create_progress
    prg = ProgressBar("Pyccuracy - %s" % **version_string**)
  File "/var/lib/python-support/python2.5/pyccuracy/colored_terminal.py", line 165, in **init**

```
raise ValueError("Terminal isn't capable enough -- you "
```

ValueError: Terminal isn't capable enough -- you should use a simpler progress dispaly.

**Comment by heynemann** [comment]
Fixed in 72856062ee0caf179c3f7fb691d8a84464e296b9
