### ISSUE TITLE
Error running on https websites

### ISSUE THREAD

**Issue by guilhermechapiewski** [heynemann/pyccuracy#35]
(Reported by Felipe Knorr Kuhn fknorr@gmail.com)

I got an error while trying to automate the login screen for one of our projects which run on https, after failing, I thought it could be because of the invalid certificate we use in the development environment, so I tried Google under https as follows:

"Como um usuário do Pyccuracy
Eu quero testar a ação de digitar um texto
Para garantir que o Pyccuracy funciona em outras línguas

Cenário 1 - Garantindo que se pode digitar em caixas de texto
Dado que
    Eu navego para "https://www.google.com"
Quando
    Eu preencho a caixa de texto "q" com "Monty Python"
Então
    #As caixas de texto estão preenchidas"

But I got the same error:

```
Dado que
    Eu navego para "https://www.google.com" - FAILED - Error executing action <bound method PageGoToAction.execute of <pyccuracy.actions.core.page_actions.PageGoToAction object at 0x844398c>> - Traceback (most recent call last):
```

  File "./pyccuracy/story_runner.py", line 87, in execute_action
    action.execute_function(context, _action.args, *_action.kwargs)
  File "./pyccuracy/actions/core/page_actions.py", line 32, in execute
  File "./pyccuracy/drivers/core/selenium_driver.py", line 58, in page_open
  File "/usr/lib/python2.5/site-packages/selenium-1.0.1-py2.5.egg/selenium.py", line 764, in open
    self.do_command("open", [url,])
  File "/usr/lib/python2.5/site-packages/selenium-1.0.1-py2.5.egg/selenium.py", line 215, in do_command
    raise Exception, data
Exception: ERROR: Command execution failure. Please search the forum at http://clearspace.openqa.org for error details from the log window.  The error message is: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIDOMLocation.href]

I'm using the Selenium jar bundled with pyccuracy, Ubuntu 8.10 and Firefox 3.0.11.

**Comment by guilhermechapiewski** [comment]
Fixed for version >= 0.6.5.
