### ISSUE TITLE
Misleading error when missing "Given,When,Then" of Scenario

### ISSUE THREAD

**Issue by gabrielfalcao** [heynemann/pyccuracy#41]
I've just figured out a very weird bug.
If the user write a test, with the story line and a scenario header, but do not write the proper lines of given, when and then, pyccuracy blews with a very misleading exception:

<pre>
0.00% - Running first test...
Traceback (most recent call last):
  File "/home/gabriel/usr/bin/pyccuracy_console", line 133, in <module>
    main()
  File "/home/gabriel/usr/bin/pyccuracy_console", line 125, in main
    verbosity=int(options.verbosity))
  File "/home/gabriel/usr/lib/python/pyccuracy/core.py", line 68, in run_tests
    fixture = self.parser.get_stories(settings)
  File "/home/gabriel/usr/lib/python/pyccuracy/parsers.py", line 53, in get_stories
    parsed, error, story = self.parse_story_file(story_file_path, settings)
  File "/home/gabriel/usr/lib/python/pyccuracy/parsers.py", line 102, in parse_story_file
    add_method = getattr(current_scenario, "add_%s" % current_area)
UnboundLocalError: local variable 'current_area' referenced before assignment
</pre>

The test that brought up that error is:

<pre>
Como um usuário
Eu quero poder alterar minha senha
Para que minha senha seja segura

Cenário 1 - Ao logar eu vejo o link de alterar senha
#Dado que
#    Eu efetuo login com o usuário "test" e senha "test"
#Quando
#    Eu navego para Pagina do Dashboard
#Então
#    Eu vejo o link "alterar_senha"
</pre>

**Comment by heynemann** [comment]
Fixed in #795e888.
